FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3.7

# Set working directory
WORKDIR /gpio-debug

# Install dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Copy main script
COPY main.py ./
CMD ["python","main.py"]
